### ISSUE TITLE
Do you any algorithm on Go?

### ISSUE THREAD

**Issue by abranhe** [AllAlgorithms/go#1]
<p align="center">
  <img src="https://cdn.abranhe.com/projects/algorithms/algorithms.svg">
</p>

Hi, everyone! 

> Do you know any algorithm implementation in any language, that you wanna share with us?

Open a pull request in any of the programming languages available, or in [Go](https://github.com/AllAlgorithms/go) this case

**Comment by rbo13** [comment]
I can also add something :)

**Comment by wolfkant** [comment]
Added simple multilayer perceptron (MLP)

**Comment by sbouchardet** [comment]
@abranhe , Could I implement huffman coding algorithm?

**Comment by abranhe** [comment]
> @abranhe , Could I implement huffman coding algorithm?

Yes, that would be great!
